baseURL: "//me.vmteam.kz/"
languageCode: en-us
title: Farkhad Dilman
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "Designer, Coding enthusiast, Soon-to-be-Doctor."
    imageUrl: "img/profile.jpg" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Posts
        url: "/posts"
      - name: My notes
        url: "https://notes.vmteam.kz/"

  homeInfoParams:
    Title: 'Hello Stranger'
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff.
  socialIcons: 
    - name: instagram
      url: 'https://instagram.com/eddiexooo/'
    - name: telegram
      url: 'https://t.me/iodiqy/'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
      